// AUTO-GENERATED node ../makeIndex.js
export * from './commands/BatchGetCommand.js';
export * from './commands/BatchWriteCommand.js';
export * from './commands/DeleteCommand.js';
export * from './commands/GetCommand.js';
export * from './commands/PutCommand.js';
export * from './commands/QueryCommand.js';
export * from './commands/ScanCommand.js';
export * from './commands/TransactGetCommand.js';
export * from './commands/TransactWriteCommand.js';
export * from './commands/UpdateCommand.js';
export * from './DynamoDBTableClient.js';
export * from './DynamoDBTableClientConfig.js';
export * from './DynamoDBTableClientResolvedConfig.js';
export * from './types.js';
export * from './util/DocumentValue.js';
export * from './util/TableClientCommandBase.js';
